### YamlMime:ManagedReference
items:
- uid: TwitterEdu.Api.Utils.ApplicationMapper
  commentId: T:TwitterEdu.Api.Utils.ApplicationMapper
  id: ApplicationMapper
  parent: TwitterEdu.Api.Utils
  children:
  - TwitterEdu.Api.Utils.ApplicationMapper.#ctor(NodaTime.IClock)
  - TwitterEdu.Api.Utils.ApplicationMapper.Now
  langs:
  - csharp
  - vb
  name: ApplicationMapper
  nameWithType: ApplicationMapper
  fullName: TwitterEdu.Api.Utils.ApplicationMapper
  type: Class
  source:
    remote:
      path: src/TwitterEdu.Api/Utils/IApplicationMapper.cs
      branch: main
      repo: https://github.com/1-IT-Gymnazium/TwitterEduApi.git
    id: ApplicationMapper
    path: ../src/TwitterEdu.Api/Utils/IApplicationMapper.cs
    startLine: 9
  assemblies:
  - TwitterEdu.Api
  namespace: TwitterEdu.Api.Utils
  syntax:
    content: 'public class ApplicationMapper : IApplicationMapper'
    content.vb: Public Class ApplicationMapper Implements IApplicationMapper
  inheritance:
  - System.Object
  implements:
  - TwitterEdu.Api.Utils.IApplicationMapper
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - TwitterEdu.Api.Utils.IApplicationMapper.TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.ToDetail(TwitterEdu.Data.Entities.Post)
- uid: TwitterEdu.Api.Utils.ApplicationMapper.#ctor(NodaTime.IClock)
  commentId: M:TwitterEdu.Api.Utils.ApplicationMapper.#ctor(NodaTime.IClock)
  id: '#ctor(NodaTime.IClock)'
  parent: TwitterEdu.Api.Utils.ApplicationMapper
  langs:
  - csharp
  - vb
  name: ApplicationMapper(IClock)
  nameWithType: ApplicationMapper.ApplicationMapper(IClock)
  fullName: TwitterEdu.Api.Utils.ApplicationMapper.ApplicationMapper(NodaTime.IClock)
  type: Constructor
  source:
    remote:
      path: src/TwitterEdu.Api/Utils/IApplicationMapper.cs
      branch: main
      repo: https://github.com/1-IT-Gymnazium/TwitterEduApi.git
    id: .ctor
    path: ../src/TwitterEdu.Api/Utils/IApplicationMapper.cs
    startLine: 9
  assemblies:
  - TwitterEdu.Api
  namespace: TwitterEdu.Api.Utils
  syntax:
    content: public ApplicationMapper(IClock Clock)
    parameters:
    - id: Clock
      type: NodaTime.IClock
    content.vb: Public Sub New(Clock As IClock)
  overload: TwitterEdu.Api.Utils.ApplicationMapper.#ctor*
  nameWithType.vb: ApplicationMapper.New(IClock)
  fullName.vb: TwitterEdu.Api.Utils.ApplicationMapper.New(NodaTime.IClock)
  name.vb: New(IClock)
- uid: TwitterEdu.Api.Utils.ApplicationMapper.Now
  commentId: P:TwitterEdu.Api.Utils.ApplicationMapper.Now
  id: Now
  parent: TwitterEdu.Api.Utils.ApplicationMapper
  langs:
  - csharp
  - vb
  name: Now
  nameWithType: ApplicationMapper.Now
  fullName: TwitterEdu.Api.Utils.ApplicationMapper.Now
  type: Property
  source:
    remote:
      path: src/TwitterEdu.Api/Utils/IApplicationMapper.cs
      branch: main
      repo: https://github.com/1-IT-Gymnazium/TwitterEduApi.git
    id: Now
    path: ../src/TwitterEdu.Api/Utils/IApplicationMapper.cs
    startLine: 11
  assemblies:
  - TwitterEdu.Api
  namespace: TwitterEdu.Api.Utils
  example: []
  syntax:
    content: public Instant Now { get; }
    parameters: []
    return:
      type: NodaTime.Instant
    content.vb: Public ReadOnly Property Now As Instant
  overload: TwitterEdu.Api.Utils.ApplicationMapper.Now*
  implements:
  - TwitterEdu.Api.Utils.IApplicationMapper.Now
references:
- uid: TwitterEdu.Api.Utils
  commentId: N:TwitterEdu.Api.Utils
  href: TwitterEdu.html
  name: TwitterEdu.Api.Utils
  nameWithType: TwitterEdu.Api.Utils
  fullName: TwitterEdu.Api.Utils
  spec.csharp:
  - uid: TwitterEdu
    name: TwitterEdu
    href: TwitterEdu.html
  - name: .
  - uid: TwitterEdu.Api
    name: Api
    href: TwitterEdu.Api.html
  - name: .
  - uid: TwitterEdu.Api.Utils
    name: Utils
    href: TwitterEdu.Api.Utils.html
  spec.vb:
  - uid: TwitterEdu
    name: TwitterEdu
    href: TwitterEdu.html
  - name: .
  - uid: TwitterEdu.Api
    name: Api
    href: TwitterEdu.Api.html
  - name: .
  - uid: TwitterEdu.Api.Utils
    name: Utils
    href: TwitterEdu.Api.Utils.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: TwitterEdu.Api.Utils.IApplicationMapper
  commentId: T:TwitterEdu.Api.Utils.IApplicationMapper
  parent: TwitterEdu.Api.Utils
  href: TwitterEdu.Api.Utils.IApplicationMapper.html
  name: IApplicationMapper
  nameWithType: IApplicationMapper
  fullName: TwitterEdu.Api.Utils.IApplicationMapper
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: TwitterEdu.Api.Utils.IApplicationMapper.TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.ToDetail(TwitterEdu.Data.Entities.Post)
  commentId: M:TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.ToDetail(TwitterEdu.Api.Utils.IApplicationMapper,TwitterEdu.Data.Entities.Post)
  parent: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions
  definition: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.ToDetail(TwitterEdu.Api.Utils.IApplicationMapper,TwitterEdu.Data.Entities.Post)
  href: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.html#TwitterEdu_Api_Models_Posts_DetailPostModelExtensions_ToDetail_TwitterEdu_Api_Utils_IApplicationMapper_TwitterEdu_Data_Entities_Post_
  name: ToDetail(IApplicationMapper, Post)
  nameWithType: DetailPostModelExtensions.ToDetail(IApplicationMapper, Post)
  fullName: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.ToDetail(TwitterEdu.Api.Utils.IApplicationMapper, TwitterEdu.Data.Entities.Post)
  spec.csharp:
  - uid: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.ToDetail(TwitterEdu.Api.Utils.IApplicationMapper,TwitterEdu.Data.Entities.Post)
    name: ToDetail
    href: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.html#TwitterEdu_Api_Models_Posts_DetailPostModelExtensions_ToDetail_TwitterEdu_Api_Utils_IApplicationMapper_TwitterEdu_Data_Entities_Post_
  - name: (
  - uid: TwitterEdu.Api.Utils.IApplicationMapper
    name: IApplicationMapper
    href: TwitterEdu.Api.Utils.IApplicationMapper.html
  - name: ','
  - name: " "
  - uid: TwitterEdu.Data.Entities.Post
    name: Post
  - name: )
  spec.vb:
  - uid: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.ToDetail(TwitterEdu.Api.Utils.IApplicationMapper,TwitterEdu.Data.Entities.Post)
    name: ToDetail
    href: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.html#TwitterEdu_Api_Models_Posts_DetailPostModelExtensions_ToDetail_TwitterEdu_Api_Utils_IApplicationMapper_TwitterEdu_Data_Entities_Post_
  - name: (
  - uid: TwitterEdu.Api.Utils.IApplicationMapper
    name: IApplicationMapper
    href: TwitterEdu.Api.Utils.IApplicationMapper.html
  - name: ','
  - name: " "
  - uid: TwitterEdu.Data.Entities.Post
    name: Post
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.ToDetail(TwitterEdu.Api.Utils.IApplicationMapper,TwitterEdu.Data.Entities.Post)
  commentId: M:TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.ToDetail(TwitterEdu.Api.Utils.IApplicationMapper,TwitterEdu.Data.Entities.Post)
  href: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.html#TwitterEdu_Api_Models_Posts_DetailPostModelExtensions_ToDetail_TwitterEdu_Api_Utils_IApplicationMapper_TwitterEdu_Data_Entities_Post_
  name: ToDetail(IApplicationMapper, Post)
  nameWithType: DetailPostModelExtensions.ToDetail(IApplicationMapper, Post)
  fullName: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.ToDetail(TwitterEdu.Api.Utils.IApplicationMapper, TwitterEdu.Data.Entities.Post)
  spec.csharp:
  - uid: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.ToDetail(TwitterEdu.Api.Utils.IApplicationMapper,TwitterEdu.Data.Entities.Post)
    name: ToDetail
    href: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.html#TwitterEdu_Api_Models_Posts_DetailPostModelExtensions_ToDetail_TwitterEdu_Api_Utils_IApplicationMapper_TwitterEdu_Data_Entities_Post_
  - name: (
  - uid: TwitterEdu.Api.Utils.IApplicationMapper
    name: IApplicationMapper
    href: TwitterEdu.Api.Utils.IApplicationMapper.html
  - name: ','
  - name: " "
  - uid: TwitterEdu.Data.Entities.Post
    name: Post
  - name: )
  spec.vb:
  - uid: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.ToDetail(TwitterEdu.Api.Utils.IApplicationMapper,TwitterEdu.Data.Entities.Post)
    name: ToDetail
    href: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.html#TwitterEdu_Api_Models_Posts_DetailPostModelExtensions_ToDetail_TwitterEdu_Api_Utils_IApplicationMapper_TwitterEdu_Data_Entities_Post_
  - name: (
  - uid: TwitterEdu.Api.Utils.IApplicationMapper
    name: IApplicationMapper
    href: TwitterEdu.Api.Utils.IApplicationMapper.html
  - name: ','
  - name: " "
  - uid: TwitterEdu.Data.Entities.Post
    name: Post
  - name: )
- uid: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions
  commentId: T:TwitterEdu.Api.Models.Posts.DetailPostModelExtensions
  parent: TwitterEdu.Api.Models.Posts
  href: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions.html
  name: DetailPostModelExtensions
  nameWithType: DetailPostModelExtensions
  fullName: TwitterEdu.Api.Models.Posts.DetailPostModelExtensions
- uid: TwitterEdu.Api.Models.Posts
  commentId: N:TwitterEdu.Api.Models.Posts
  href: TwitterEdu.html
  name: TwitterEdu.Api.Models.Posts
  nameWithType: TwitterEdu.Api.Models.Posts
  fullName: TwitterEdu.Api.Models.Posts
  spec.csharp:
  - uid: TwitterEdu
    name: TwitterEdu
    href: TwitterEdu.html
  - name: .
  - uid: TwitterEdu.Api
    name: Api
    href: TwitterEdu.Api.html
  - name: .
  - uid: TwitterEdu.Api.Models
    name: Models
    href: TwitterEdu.Api.Models.html
  - name: .
  - uid: TwitterEdu.Api.Models.Posts
    name: Posts
    href: TwitterEdu.Api.Models.Posts.html
  spec.vb:
  - uid: TwitterEdu
    name: TwitterEdu
    href: TwitterEdu.html
  - name: .
  - uid: TwitterEdu.Api
    name: Api
    href: TwitterEdu.Api.html
  - name: .
  - uid: TwitterEdu.Api.Models
    name: Models
    href: TwitterEdu.Api.Models.html
  - name: .
  - uid: TwitterEdu.Api.Models.Posts
    name: Posts
    href: TwitterEdu.Api.Models.Posts.html
- uid: TwitterEdu.Api.Utils.ApplicationMapper.#ctor*
  commentId: Overload:TwitterEdu.Api.Utils.ApplicationMapper.#ctor
  href: TwitterEdu.Api.Utils.ApplicationMapper.html#TwitterEdu_Api_Utils_ApplicationMapper__ctor_NodaTime_IClock_
  name: ApplicationMapper
  nameWithType: ApplicationMapper.ApplicationMapper
  fullName: TwitterEdu.Api.Utils.ApplicationMapper.ApplicationMapper
  nameWithType.vb: ApplicationMapper.New
  fullName.vb: TwitterEdu.Api.Utils.ApplicationMapper.New
  name.vb: New
- uid: NodaTime.IClock
  commentId: T:NodaTime.IClock
  parent: NodaTime
  isExternal: true
  href: https://github.com/jskeet/nodatime/blob/4d0e4c04dd5f09304a7e53a0675dce1597ea0143/src/NodaTime/IClock.cs
  name: IClock
  nameWithType: IClock
  fullName: NodaTime.IClock
- uid: NodaTime
  commentId: N:NodaTime
  isExternal: true
  name: NodaTime
  nameWithType: NodaTime
  fullName: NodaTime
- uid: TwitterEdu.Api.Utils.ApplicationMapper.Now*
  commentId: Overload:TwitterEdu.Api.Utils.ApplicationMapper.Now
  href: TwitterEdu.Api.Utils.ApplicationMapper.html#TwitterEdu_Api_Utils_ApplicationMapper_Now
  name: Now
  nameWithType: ApplicationMapper.Now
  fullName: TwitterEdu.Api.Utils.ApplicationMapper.Now
- uid: TwitterEdu.Api.Utils.IApplicationMapper.Now
  commentId: P:TwitterEdu.Api.Utils.IApplicationMapper.Now
  parent: TwitterEdu.Api.Utils.IApplicationMapper
  href: TwitterEdu.Api.Utils.IApplicationMapper.html#TwitterEdu_Api_Utils_IApplicationMapper_Now
  name: Now
  nameWithType: IApplicationMapper.Now
  fullName: TwitterEdu.Api.Utils.IApplicationMapper.Now
- uid: NodaTime.Instant
  commentId: T:NodaTime.Instant
  parent: NodaTime
  isExternal: true
  href: https://github.com/jskeet/nodatime/blob/4d0e4c04dd5f09304a7e53a0675dce1597ea0143/src/NodaTime/Instant.cs
  name: Instant
  nameWithType: Instant
  fullName: NodaTime.Instant
